#访问端口
server:
  port: 8077
#mybatis的配置
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    type-aliases-package: com.jf.mydemo.entity.*
#    mapper-locations: mapper/*.xml
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
 #实体类所做包
  typeAliasesPackage: com.jf.mydemo.entity
# #mapper.xml所在位置
  mapperLocations: classpath:mapper/*.xml
  logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  executor-type: simple
#spring配置
#日志相关的配置
logging:
  pattern:
    console: "%d - %msg%n"
  #path: e:/
  file: e:/testLog.log
  level:
    #这里可以是包名也可以是类名
    com.lonely: debug